### ISSUE TITLE
Which options are "input options"?

### ISSUE THREAD

**Issue by cwebber** [w3c/vc-data-integrity#16]
The [Create Verify Hash Algorithm](https://w3c-dvcg.github.io/ld-signatures/#create-verify-hash-algorithm) mentions "input options", distinct from signature options apparently, seemingly out of nowhere.  It turns out these options are a subset of the possible options available to the signature/verify algorithms, and on verify in fact appear to come from the key and signature of the object being verified mostly itself.  However nowhere else in the document is this mentioned, and which keys to extract, and from where, is not spelled out.

In practice from jsonld-signatures.js we can see that they are the following:

``` javascript
      {
        algorithm: algorithm,
        privateKeyPem: privateKeyPem,
        privateKeyWif: privateKeyWif,
        date: date,
        nonce: nonce,
        domain: domain
      }
```

We should specify how to extract these from what in the verify/signature sections when explaining that they must be passed into Create Verify Hash.  It may also be that some of these values may be different depending on the signature suite used, so we should specify some way that the suite can determine how/where to "extract" these values.

**Comment by wip-abramson** [comment]
I also find myself confused by this.

`Input options` appears out of nowhere. It is not defined in the Terminology section. 

I am unclear what the relationship between `proof options` and `input options`

The text from the spec is:

> It takes a canonicalized [unsigned data document](https://w3c.github.io/vc-data-integrity/#dfn-unsigned-data-document), canonicalized document, [canonicalization algorithm](https://w3c.github.io/vc-data-integrity/#dfn-canonicalization-algorithm), a [message digest algorithm](https://w3c.github.io/vc-data-integrity/#dfn-message-digest-algorithm), and [proof options](https://w3c.github.io/vc-data-integrity/#dfn-proof-options), input options (by reference). The [proof options](https://w3c.github.io/vc-data-integrity/#dfn-proof-options) MUST contain an identifier for the public/private key pair, and an [[ISO8601](https://w3c.github.io/vc-data-integrity/#bib-iso8601)] combined date and time string, created, containing the current date and time, accurate to at least one second, in Universal Time Code format.

So are input options just proof options? Or are they proof options, message digest algorithm and canonicalization algorithm?

Or are they the options that I pass into the RDF canonicalization? 

```
jsonld.normalize(
    output, 
   {'algorithm': 'URDNA2015', 'format': 'application/n-quads'} << THESE OPTIONS?
)
```
Or something else?

**Comment by msporny** [comment]
There has been some fairly significant re-work and finalization of the algorithms used in the specification since this issue was raised. We no longer use `input options` in the specification at all. The `proof options` are defined here now: https://www.w3.org/TR/vc-data-integrity/#add-proof and are used throughout the cryptosuite-specific algorithms. Here's an example of them being used in the EdDSA cryptosuite (search for "proof options"):

https://www.w3.org/TR/vc-di-eddsa/

All that to say, there is no such thing as "input options" anymore (the topic of this issue), and the use of "proof options" are detailed far more now (both in the Data Integrity spec as well as the cryptosuite specifications).

I'm marking this issue with a "pending 7 day close", please let us know if there is something more that needs to be done to resolve this issue. If not, the issue will be closed in 7 days (but you can feel free to re-open it if you think there is more that needs to be done).
