### ISSUE TITLE
Correct statements about standardization of multibase and multihash

### ISSUE THREAD

**Issue by selfissued** [w3c/vc-data-integrity#192]
A note in the spec currently says:
> (FEATURE AT RISK) ISSUE: Multibase and Multihash are being standardized at IETF
> The [[MULTIBASE](https://w3c.github.io/vc-data-integrity/#bib-multibase)] and [[MULTIHASH](https://w3c.github.io/vc-data-integrity/#bib-multihash)] specifications have been dispatched at IETF to be standardized in a [Multiformats Working Group](https://mailarchive.ietf.org/arch/browse/multiformats/).

There is no IETF Multiformats working group and it's up to the IESG whether there ever will be one.

Please change "are being standardized" to "may be standardized".

And please change "have been dispatched at IETF to be standardized in a [Multiformats Working Group](https://mailarchive.ietf.org/arch/browse/multiformats/)" to "are being discussed in a [Multiformats mailing list](https://mailarchive.ietf.org/arch/browse/multiformats/)".

Then the statements will be accurate.

**Comment by OR13** [comment]
previously discussed in https://github.com/w3c/vc-data-integrity/pull/92

Which later led to:

- https://github.com/w3c/vc-data-model/issues/1261
- https://github.com/w3c/vc-data-model/issues/1175

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-14-vcwg#section3-2) on 2023-09-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.2. Correct statements about standardization of multibase and multihash (issue vc-data-integrity#192)

_See github issue [vc-data-integrity#192](https://github.com/w3c/vc-data-integrity/issues/192)._




**Michael Jones:** the spec includes a note saying multibase/hash are being standardized at the IETF in a multiformats WG. for the record, there is no multiformats WG, there is a mailing list. it is up to the IESG to create a group. we should be accurate in what we're saying.  

> *Sebastian Crane:* +1 to these changes for clarity. Happy to be assigned.

**Michael Jones:** change to say 'it may be standardized' and another to correctly cite its a mailing list not a wg.  

**Manu Sporny:** +1 to those changes.  

**Brent Zundel:** can continue on with manu's presentation and move towards proposals.  

</details>

**Comment by msporny** [comment]
PR #197 has been raised to address this issue. This issue will be closed once PR #197 has been merged.

**Comment by msporny** [comment]
PR #197 has been merged, closing.
