### ISSUE TITLE
Specifying that input document must be framed or compacted in algorithm?

### ISSUE THREAD

**Issue by cwebber** [w3c/vc-data-integrity#20]
Best I can tell to actually implement the appropriate signature/verification algorithms you need to compact or frame the input document, but that isn't specified.  Maybe it's obvious and doesn't need to be?  Maybe it should be spelled out though, especially if framing, so the person implementing can properly find the "root" of the graph being signed.

**Comment by msporny** [comment]
The algorithms for verification now exist, and do not mention framing/normalizing the input document (because Data Integrity is no longer an RDF-only solution, you can use it to sign/verify regular JSON messages that are canonicalized using JCS). There is a presumption that you're getting an object in that has a proof defined at the top level... if you don't have that the verification check will fail:

https://w3c.github.io/vc-data-integrity/#verify-proof

Closing given that we now specify the algorithm for verifying the proof (and it presumes transformations have already been made when the signature check is performed). If they haven't, the verification fails closed (that is, the signature fails to verify).
