### ISSUE TITLE
I think the diagram key should be changed from `Graph Containment` to `Contains`

### ISSUE THREAD

**Issue by TallTed** [w3c/vc-data-integrity#203]
_Originally posted by @TallTed and @iherman in https://github.com/w3c/vc-data-integrity/pull/189#discussion_r1320024393_

>> [@TallTed] `styled as Contains` makes me think the key should be changed from `Graph Containment`, which change I was going to suggest anyway.
>
> [@iherman] I agree, but I would prefer to move that into a separate issue. The reason is that, for consistency's sake, this change should also be done in the VCDM, both in the descriptions and on the diagrams, and I do not want to mess up this PR for that. Would you agree? If so, can you put that into a separate issue? Thx.

**Comment by iherman** [comment]
@TallTed I have made the changes on my "core" versions, see

https://drive.google.com/drive/folders/1dR194S3hPJZmPNpOcMtXKVMIX2JnwYGZ?usp=sharing

If you look at those, you will realize that I went back to black and white. After some experimentation with different dark mode generation styles, bw seems to be the only secure and accessible option. Under some types of dark modes the previous version became unreadable...

**Comment by iherman** [comment]
As an aside: keeping these files on a Google Drive may not be the best idea. It is difficult to keep track with the various PR-s involving vocabularies while having a single places to the Google Drive. @msporny, as main manager of these two repositories, would it be o.k. to store the drawio and SVG files in the repo, thereby having different versions? The only annoying aspect is that the generation of the SVG file must be made outside GitHub; I do not think there is a command-line option to generate the SVG file which, due to a current bug in drawio, must go through a separate script anyway.

@msporny wdyt?

**Comment by iherman** [comment]
@TallTed I hope it is all right that this has been marked as pending close

**Comment by msporny** [comment]
> @msporny, as main manager of these two repositories, would it be o.k. to store the drawio and SVG files in the repo, thereby having different versions?

Yes, that's fine w/ me. Best to keep source files in the repository. Having to re-generate the SVG isn't great, but I expect we won't need to do that too often.

**Comment by iherman** [comment]
> > @msporny, as main manager of these two repositories, would it be o.k. to store the drawio and SVG files in the repo, thereby having different versions?
> 
> Yes, that's fine w/ me. Best to keep source files in the repository. Having to re-generate the SVG isn't great, but I expect we won't need to do that too often.

After the dust settles, I do not expect much change. I may add a README in the repository's folder to describe what is happening.

Next time I raise a PR related to a vocabulary, I will add these. I do not think it is worth raising a PR just for that...

**Comment by brentzundel** [comment]
No objections raised to closing since marked as `pending close`, closing.
