### ISSUE TITLE
Add language about verificationMethod representation

### ISSUE THREAD

**Issue by OR13** [w3c/vc-data-integrity#25]
https://w3c-ccg.github.io/ld-proofs/#verification-method

Need to explain how to support publicKeyBase58, publicKeyHex, publicKeyJwk, etc... need to make this much clearer... see also: https://github.com/w3c-ccg/lds-jws2020/issues/11

**Comment by OR13** [comment]
See comments on: https://github.com/w3c-ccg/ld-cryptosuite-registry/issues/3

**Comment by msporny** [comment]
@OR13 does something like this help?

https://w3c.github.io/vc-di-eddsa/#verification-methods

Or would you like to see that text moved into the VC Data Integrity spec? I believe I'd prefer to see language in the cryptosuite specs moved to the data integrity spec so that cryptosuite specs can just re-use the same key base definitions in VC Data Integrity. Cryptosuites can always invent their own key material if they'd like, but having a common understanding around Multikey, JsonWebKey, and other key formats might be helpful.

How would you like to resolve this issue?

**Comment by OR13** [comment]
The spec has this now: https://www.w3.org/TR/vc-data-integrity/#controller-documents

I am closing this as complete.
