### ISSUE TITLE
either nonce or challenge is redundant

### ISSUE THREAD

**Issue by awoie** [w3c/vc-data-integrity#30]
The current spec uses both, `challenge` and `nonce` properties. Why is this needed? Would it make sense to encourage only one of them?

**Comment by msporny** [comment]
The specification has removed the use of `nonce`. Only the `challenge` property remains. Closing.

**Comment by awoie** [comment]
I actually might want to reopen the issue since I think it might be useful to have a challenge that prevents against replay and a holder-selected nonce that prevents tracking based on the signature value.

**Comment by awoie** [comment]
Feel free to close this issue and open a new issue that defines an optional holder-selected nonce to mitigate some privacy concerns. It is not really a big concern though but it would be nice to give implementer's the option at least.

**Comment by msporny** [comment]
Hey @awoie, checking in on whether or not you still want this feature? If so, I'll close this issue and open a new one to re-define nonce (or some signer-supplied value).

I'm going to mark this pending 7 day close since it's going to be closed either way. Feel free to open a new issue to define the holder-provided data mechanism you'd like to see in the specification.
