### ISSUE TITLE
`expires` proof property lacks examples and vocab mapping

### ISSUE THREAD

**Issue by filip26** [w3c/vc-data-integrity#313]
There is no single example using `expires` and no vocabulary mapping defined except `@context` itself. 

The lack of examples and vocab mapping could lead to adoption issues - please note `expires` expands to `https://w3id.org/security#expiration`  and not to `https://w3id.org/security#expires`

**Comment by msporny** [comment]
PR #314 has been raised to address this issue. This issue will be closed once PR #314 has been merged.

**Comment by iherman** [comment]
Just for the records:

> There is no single example using expires and no vocabulary mapping defined except `@context` itself.

There is a bona fide definition of the property in the official [vocabulary](https://w3c.github.io/vc-data-integrity/vocab/security/vocabulary.html#expiration). It is an unfortunate historical (and backward compatibility) problem that the term `expiration` is used in the vocabulary, but that is only an aesthetic problem.

So if #314 is merged, the issue is indeed fully handled.

**Comment by msporny** [comment]
PR #314 has been merged, closing.
