### ISSUE TITLE
Clarifying `challenge` property

### ISSUE THREAD

**Issue by lemoustachiste** [w3c/vc-data-integrity#324]
Hey,

I just wanted to make sure I understood what the objective of `challenge` is.

As I understand it, it's a value that is generated by the issuer and put into the proof.
It's to be used in conjunction with the `proofPurpose` `authentication`, and it's just a string comparison.

As such I suppose I need to understand more the context in which it's being used:
- ~~it's rather short lived (meaning it cannot remain valid _ad vitam_)?~~  it's right there in the spec...
- ~~Is it a one time only property?~~ it's right there in the spec...
- How does the verifier get to know the value it should compare against? 
- Is the general purpose to be a sort of replacement of Web Tokens for instance?

Thanks for your help.

**Comment by dlongley** [comment]
> As I understand it, it's a value that is generated by the issuer and put into the proof.

No, it's generated by the verifier and communicated to the holder using in a protocol-specific manner. For example, it can be communicated in a VPR (Verifiable Presentation Request) using the VC API.

> It's to be used in conjunction with the `proofPurpose` `authentication`, and it's just a string comparison.

That's right. This is why it's provided by the verifier -- and the holder is expected to generate a VP (Verifiable Presentation) with a proof over that VP that includes `proofPurpose` `authentication` and the `challenge` value (and other things, e.g., `domain`) in order to authenticate themselves to the verifier.

> How does the verifier get to know the value it should compare against?

As noted above, it's the verifier that generates the `challenge`, so they have this value.

> Is the general purpose to be a sort of replacement of Web Tokens for instance?

No, the goal isn't to create or replace oauth access tokens (I presume this is what you mean by "Web Tokens"), but just to perform authentication, often potentially at the same as a holder presents one or more VCs (or other information) in a VP. In fact, one thing a user might receive after authenticating themselves (and optionally providing VCs) is some kind of access token (or a zcap, aka "capability") to access a resource.

**Comment by lemoustachiste** [comment]
Thanks, that helps a lot
