### ISSUE TITLE
Enable GitHub Pages so we can use it to serve old URLs like https://w3c-ccg.github.io/ld-proofs

### ISSUE THREAD

**Issue by gobengo** [w3c/vc-data-integrity#39]
Context: clicking reference [LD-PROOFS] https://w3c-ccg.github.io/di-eddsa-2020/#normative-references

I click https://w3c-ccg.github.io/ld-proofs -> redirect to https://w3c.github.io/data-integrity/
Get 404.

But go to repo: https://github.com/w3c/data-integrity
redirects to: https://github.com/w3c/vc-data-integrity

I think it's because this w3c/vc-data-integrity repo doesn't have gh-pages enabled?

Can we enable github pages so we can try to make the old URLs redirect to the new ones?

**Comment by gobengo** [comment]
@OR13 told me the 404 may be because this repo doesn't have gh pages

**Comment by OR13** [comment]
Sometimes W3C uses echidna to publish, maybe that needs to be setup in this case. 

@iherman when do we use echidna and when do we use GitHub pages?

**Comment by iherman** [comment]
The right target URL should be https://w3c.github.io/vc-data-integrity/ (as opposed to https://w3c.github.io/data-integrity/). Someone has to update the ccg document.

The reason of the discrepancy was a renaming round of the repository while transitioning it to W3C. Github does an automatic redirection for the github repository itself after renaming, but not for the github pages. And, because the repository w3c/data-integrity does not exist anymore (it was ephemeral...), it is not possible to set up pages for it.

This has nothing to do with echidna, b.t.w. Echidna is used to automatically publish a document on the W3C /TR pages, and we will certainly set it up for the data integrity spec as soon as it is officially published as a FPWD.

**Comment by msporny** [comment]
This is fixed, just needed to update the CCG ld-proofs redirect.
