### ISSUE TITLE
Add at least one unsigned properties

### ISSUE THREAD

**Issue by jandrieu** [w3c/vc-data-integrity#90]
There are use cases for selective disclosure in which a "VC" needs auxiliary information beyond what is signed to travel along with the signed VC when delivered to the holder. The holder selects which data, if any, to forward along to a verifier in a derived VC presented in a Verifiable Presentation.

In other words, the issuer coordinator generates a proto-VC, which includes (in our use case) a merkle root. That proto-VC is sent to the issuer service, signed, and returned to the issuer coordinator. The resulting VC is then augmented by the coordinator, adding fields that are important to the holder but not part of the explicitly signed JSON data. In our case, these fields are the selectable data that the holder MUST know to perform selective disclosure, but which is not directly signed by the data integrity proof of the VC.

**Comment by dlongley** [comment]
This is interesting. It seems that there may be multiple ways to do this.

Indeed, there are other proof types (BBS, maybe?) that have proof properties that only the holder sees and uses. I know there are also some proof types that have thus far only been considered (but not fully designed or implemented yet) that would also have properties that only the holder uses. These properties would not be signed over in the proof but removed and only used by the holder during presentation.

It could be that this could be addressed entirely in the data integrity spec instead of the core data model, so perhaps the issue should be moved there. As for working with issue coordinators to generate such proofs, if any such "unsigned parameters" are needed to be sent to an issuing service, perhaps they could be sent alongside a credential rather than needing it to travel within, especially if they are to be removed (it's unclear if that also matches the case you describe).

**Comment by jandrieu** [comment]
Ideally, the unsigned parameters are NOT sent to the issuer service, in part to prevent an additional data processor from having access to potentially personal data. So, the coordinator sends the entire signable proto-VC, but keeps the selectable data to itself at first. Then, it adds the selectable data to the signed VC, which is sent to the holder. 

I basically just want a standardized way to have a property that is not "secured" by the integrity proof.

I'm ok if the right place to do it is in the data integrity spec.

**Comment by dlongley** [comment]
Sounds like it should be moved to the data integrity spec.

**Comment by RieksJ** [comment]
Curious to learn what such a use-case would be. And what warrants that this would be within the scope of the VCDM spec. Why not do this elsewhere, similar to that the presentation exchange spec limits its scope to presentation requests and responses (data structures), and leaves additional data that is needed in transactions (e.g. a transaction identifier/nonce) outside of its scope?

**Comment by Sakurann** [comment]
agreed to move this to data-integrity

**Comment by jandrieu** [comment]
> Curious to learn what such a use-case would be. And what warrants that this would be within the scope of the VCDM spec. Why not do this elsewhere, similar to that the presentation exchange spec limits its scope to presentation requests and responses (data structures), and leaves additional data that is needed in transactions (e.g. a transaction identifier/nonce) outside of its scope?

The use case is selective disclosure.

The signed VC contains a commitment to the disclosable properties. Call it "commitment". That could be a string of hashes, a merkle root, any kind of cryptographic commitment. This commitment MUST be signed over, which uses the familiar VC proof mechanism.

The logical VC contains the signed VC *plus* a property we'll call "disclosable" which contains the properties and associated proofs so that the holder can select & choose which disclosable properties to reveal.

To compose the derived VC that is presented in the VP, we combine the signed VC with one or more disclosables and the verifier can verify that the signed VC verifies the commitment (commitment hasn't changed since issuance) and that the disclosable properties are provably in that commitment, resulting in verification of selectively disclosed properties.

I can currently achieve this two-part mechanism this by transmitting the signed VC and the disclosables separately all the way from issuer to verifier. The holder would be responsible for keeping those disclosables around until needed.  We would minimize the risk of separating the disclosables from their signed VC if the disclosables were actually listed as a property in the signed VC, but which the signature ignores.

Dave Longley suggested these properties probably go in the data integrity proof section, which sounds right, since the proof properties are not themselves signed over. 

@RieksJ the main reason to do this in the VC itself is simply data management. The usable VC is not just the signed VC, it must include the disclosables or the holder doesn't know how to compose the derived VC. If you separate the signed part from the unsigned part, you're just asking for errors, and since the two are nearly useless without the other (disclosables without the signed VC are unprovable and the signed VC without at least one disclosable is just a regular VC without selective disclosure), I'd like to have them in the same data object transferred at a single point in time and most likely stored as a single object in the holder's wallet.

**Comment by silverpill** [comment]
This will be useful in cases where ID of the object depends on the hash of the signed document. Example:

```json
{
  "type": "Note",
  "content": "test",
  "proof": {
    "type": "DataIntegrityProof",
    "cryptosuite": "jcs-eddsa-2022",
    "excluded": ["id"],
    ...
  }
}
```

The author then hashes entire document and inserts the ID:

```json
{
  "id": "urn:sha256:aa00bb11",
  "type": "Note",
  "content": "test",
  "proof": {
    "type": "DataIntegrityProof",
    "cryptosuite": "jcs-eddsa-2022",
    "excluded": ["id"],
    ...
  }
}
```

Other documents can contain references to this document:

```json
{
  "id": "urn:sha256:bb22cc33",
  "type": "Note",
  "content": "reply to test",
  "inReplyTo": "urn:sha256:aa00bb11"
}
```
Given a content-addressed storage system, one can discover referenced documents and verify their integrity and authorship.

**Comment by msporny** [comment]
@jandrieu wrote:
> The use case is selective disclosure.

The `proofValue` isn't signed over, so that's where these "unsigned properties" could go... at least, that's where we put them for [ecdsa-sd-2023](https://docs.google.com/presentation/d/1d-04kIWhPuNscsAyUuRH3pduqrNerhigCWahKe6SNos/edit). Implementation examples here:

https://github.com/digitalbazaar/ecdsa-sd-2023-cryptosuite#readme

Taking that approach provided a fairly clean interface. Ultimately, it's up to the cryptosuite to decide what it signs over and what it doesn't, so this is probably not an issue for the base data integrity spec. By default, we very strongly recommend that you sign over everything. Having unsigned properties in multiple places, especially in the VC, will almost inevitably result in security failures (because people will use the unsigned property without knowing that it wasn't secured).

I'd like to close this issue because:

* This is really up to the cryptosuite to decide what NOT to sign, at present, all cryptosuites don't sign the `proofValue` because, well, that's the only piece of information that's unsignable.
* Having unsigned properties scattered in the secured object is a bad practice because developers might use the unsigned value w/o knowing it was unsigned. 

The current proposal is to close this issue for the reasons above. Thoughts?

**Comment by silverpill** [comment]
@msporny In other words, the proposed solution for the use case I described above is to create a new cryptosuite (e.g. `jcs-eddsa-without-id-2023`)?

**Comment by msporny** [comment]
@silverpill wrote:
> @msporny In other words, the proposed solution for the use case I described above is to create a new cryptosuite (e.g. `jcs-eddsa-without-id-2023`)?

At present, that would be one way to do it, but I'd suggest that's not a good pattern to follow. Remember, one of the goals of data integrity proofs is to secure everything in the message (as a general rule)... the second you stop securing something, you open up the possibility that someone is going to use a value without knowing if it's secured or not. In other words, you create something an attacker can exploit. Cryptographic hashes are not an exception, even if it seems like they might be at first. IOW, if you just check that the hash matches the message, and you don't check who signed the message (and that you trust them), then you can't trust the cryptographic hash either (an attacker can just create their own fake message and set the correct cryptographic hash for that message).

It's better for your application software to add/remove things BEFORE or AFTER the cryptographic process. Have you considered the following alternatives:

* Make the identifier a UUID and then sign that. The thing you're trusting here is the individual that signed the UUID, not the UUID itself, right?
* Add or remove the `id` property before/after you do the digital signature process. Because it's a hash that points to digitally signed data, you don't need to secure the hash and it can be added/removed at any time (at the application layer, not the cryptographic layer)... but in order to trust the hash, you have to trust the signer of the information. IOW, you have to check both (hash and signer is someone you trust).

**Comment by silverpill** [comment]
The `id` needs to be dereferencable, so UUIDs are not suitable, but I think adding/removing `id` at the application layer could work.
Thanks for your feedback!

**Comment by msporny** [comment]
@jandrieu after waiting for feedback for two weeks, I'm marking this as pending 7 day close. A proposed answer to your questions is here (and it seems that those involved in the thread agree with closing):

https://github.com/w3c/vc-data-integrity/issues/90#issuecomment-1634994259

Just checking to see that you find the explanation/proposal above acceptable.
